/* projecteuler.net
 * Problem 2 
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 *
 * A. 4613732
 *
 */

#include <stdio.h>
#include <math.h>

int main(){
    int i = 0;
    double num1, num2, ans, sum = 0;
    num1 = 0;
    num2 = 1;
    
    while(ans < 4000000){
        ans = (num1 + num2);
        if(fmod(ans,2) == 0)
            sum += ans;
        num1 = num2;
        num2 = ans;
        i++;
    }
    printf("Sum of Fib seq up to 4 million: %.0lf\n", sum);

    return 0;
}
