/* projecteuler.net
 *
 * Problem 12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *   3: 1,3
 *    6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 *    We can see that 28 is the first triangle number to have over five divisors.
 *
 *    What is the value of the first triangle number to have over five hundred divisors?
 *
 *    A. 76576500
 */

#include <stdio.h> 

double gen(int i){
    int j = i-1;
    for(j; j >= 1; j--){
        i +=  j;
    }
    return i;
}

int factor_count(double tri){
    int count = 0;
    int i;
    int tri_int = tri;
    for(i=1; i*i <= tri; i++){
        if(tri_int % i == 0){
            count += 2;
        }
    }
    return count;
}
int main(){
    int i = 500;
    int num_factors = 0;
    double triangle;
    while(i > 0){
        triangle = gen(i);
        num_factors = factor_count(triangle);
        if(num_factors > 500){
            printf("First triangle number with over 500 divisors: %.0f\n", triangle);
            printf("Number of divisors: %i\n", num_factors);
            return 0;
        }
        i++;
    }
}





