#!/usr/bin/env ruby
#
# projecteuler.net
#
# problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the
# following formulae:
#
# Triangle      Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal        Pn=n(3n1)/2     1, 5, 12, 22, 35, ...
# Hexagonal     Hn=n(2n1)       1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
#

class Triangle
    def initialize
        @n = 1
    end

    def isTriangle?(n)
    end

    def next
        tri = @n * (@n + 1) / 2
        @n += 1
        tri
    end
end

class Pentagonal
    def initialize
        @n = 1
    end

    def next
        pent = @n * (3 * @n - 1) / 2
        @n += 1
        pent
    end
end

class Hexagonal
    def initialize
        @n = 1
    end

    def next
        hex = @n * (2 * @n - 1)
        @n += 1
        hex
    end
end

tris = []
pents = []
hexes = []
all = [40755]
t = Triangle.new
p = Pentagonal.new
h = Hexagonal.new
while all.last <= 40755 do
    tris << t.next
    pents << p.next
    hexes << h.next
    all = tris & pents & hexes
end

puts all.last
