#!/usr/bin/env ruby
#
# Build helpers.c
#

require 'rubygems'
require 'rake'

task :default => [:make]

task :make do
    sh "gcc -Wall -fPIC -c `pkg-config --cflags --libs glib-2.0` \
        -fopenmp  -I. helpers.c" 

    sh "gcc -fopenmp -shared -Wl,-soname,helpers.so \
        -o helpers.so helpers.o -lm -lgmp" 

    sh "rm *.o"
end

require 'rspec/core'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |spec|
      spec.pattern = FileList['spec/**/*_spec.rb']
end
