#!/usr/bin/env ruby
#
# Build helpers.c
#

require 'rubygems'
require 'rake'
require 'rake/clean'

task :default => [:make]

task :make do
    sh "gcc -Wall -fPIC -c `pkg-config --cflags --libs glib-2.0` \
        -fopenmp  -I. pe.c" 

    sh "gcc -fopenmp -shared -Wl,-soname,libpe.so \
        -o libpe.so pe.o -lm -lgmp `pkg-config --libs glib-2.0`" 
end

CLEAN.include("*.o")
CLOBBER.include("*.so")

require 'rspec/core'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |spec|
      spec.pattern = FileList['spec/**/*_spec.rb']
end
